# readsb configuration
# Edit lat/lon to your location

RECEIVER_OPTIONS="--device-type rtlsdr --gain -10"
DECODER_OPTIONS="--max-range 450 --lat 52.0116 --lon 4.7683"
NET_OPTIONS="--net --net-heartbeat 60 --net-ro-size 1300 --net-ro-interval 0.2 --net-buffer 2"
JSON_OPTIONS="--json-location-accuracy 2"
