#!/usr/bin/env python3
"""
Convert A3_img_sm.h (RGB565 136×136, AMOLED) → A3_xbm.h (1-bit XBM for U8G2).

Run once from the FlightBoard_EPaper sketch folder:
    python convert_a3.py

The AMOLED source uses black=0x0000 for background, non-zero for the
aircraft/radar graphic. On the RLCD (white background) we map:
    0x0000  → 0 (white / leave blank)
    non-zero → 1 (draw black pixel)

Output sizes:
    A3_XBM_LG : 80×80  — for the logo bubble (88×88 bubble, 4 px margin)
    A3_XBM_SM : 48×48  — for the "no aircraft / scanning" splash
"""

import re, sys
from pathlib import Path

SRC = Path(__file__).parent / "../../esp32-amoled/arduino-radar/ESP32_Radar/A3_img_sm.h"
DST = Path(__file__).parent / "A3_xbm.h"

SRC_W, SRC_H = 136, 136

def read_pixels(path):
    text = path.read_text()
    body = re.search(r'\{([^}]+)\}', text, re.DOTALL)
    if not body:
        sys.exit(f"Could not parse array from {path}")
    raw = [int(v, 16) for v in re.findall(r'0x[0-9A-Fa-f]+', body.group(1))]
    if len(raw) != SRC_W * SRC_H:
        sys.exit(f"Expected {SRC_W*SRC_H} values, got {len(raw)}")
    return raw

def scale_nearest(src, sw, sh, dw, dh):
    """Nearest-neighbour scale from src (sw×sh 1-bit list) to dw×dh."""
    out = []
    for y in range(dh):
        row = []
        for x in range(dw):
            sx = int(x * sw / dw)
            sy = int(y * sh / dh)
            row.append(src[sy * sw + sx])
        out.append(row)
    return out

def to_xbm(pixels_2d, w, h):
    """Encode a list-of-rows to XBM bytes (LSB-first within each byte)."""
    bpr = (w + 7) // 8
    data = []
    for row in pixels_2d:
        for bi in range(bpr):
            byte = 0
            for bit in range(8):
                px = bi * 8 + bit
                if px < w and row[px]:
                    byte |= (1 << bit)   # XBM: LSB = leftmost pixel
            data.append(byte)
    return data

def write_xbm_header(path, sizes):
    """sizes = list of (name_suffix, w, h, data_bytes)"""
    lines = [
        "// Auto-generated by convert_a3.py — do not edit manually.",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
    ]
    for suffix, w, h, data in sizes:
        bpr = (w + 7) // 8
        lines += [
            f"#define A3_XBM_{suffix}_W  {w}",
            f"#define A3_XBM_{suffix}_H  {h}",
            f"static const uint8_t A3_XBM_{suffix}[] PROGMEM = {{",
        ]
        for i in range(0, len(data), bpr):
            chunk = data[i:i+bpr]
            lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
        lines += ["};", ""]
    path.write_text("\n".join(lines))
    print(f"Written {path}")

raw  = read_pixels(SRC)
bits = [1 if v != 0 else 0 for v in raw]

rows_lg = scale_nearest(bits, SRC_W, SRC_H, 80, 80)
rows_sm = scale_nearest(bits, SRC_W, SRC_H, 48, 48)

write_xbm_header(DST, [
    ("LG", 80, 80, to_xbm(rows_lg, 80, 80)),
    ("SM", 48, 48, to_xbm(rows_sm, 48, 48)),
])
