#!/usr/bin/env python3
"""
Regenerate logos.h for the ESP32 AMOLED flight board using airline logos
from the repo's images/airline_logos/ directory.

Run from the repo root (or from this sketch folder):
    python esp32-amoled/arduino-radar/ESP32_Radar/gen_logos.py

Each logo is stored as a 80x80 RGB565 uint16_t array in PROGMEM.
Only the ICAO codes listed in INCLUDE are generated (same set as the
previous logos.h, ~1.3 MB of PROGMEM data).
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Install Pillow first:  pip install Pillow")

# ── configuration ──────────────────────────────────────────────────────────────

LOGO_DIR = Path(__file__).parent / "../../../images/airline_logos"
DST      = Path(__file__).parent / "logos.h"
W = H    = 80   # pixel dimensions

# ICAO codes to include (same set as the original logos.h)
INCLUDE = [
    "AAL","AAR","ABY","ACA","AEA","AEE","AFR","AHK","AMX","ANA","ANZ","ASA",
    "ATN","AUA","AVA","AZA","AZU","BAW","BCY","BEE","BEL","BPA","BTI","CCA",
    "CES","CFG","CJT","CPA","CSA","CSN","DAL","DLH","EIN","EJU","ELY","ETD",
    "ETH","EVA","EWG","EXS","EZS","EZY","FCA","FDB","FDX","FIN","GIA","GLO",
    "HVN","IBE","IBS","ICE","JAL","JBU","KAC","KAL","KLM","KQA","LAM","LAN",
    "LBT","LOT","MAS","MEA","MSR","NAX","NOZ","OAL","OAW","PAL","PGT","QFA",
    "QTR","RAM","RJA","ROT","RYR","SAA","SAS","SIA","SVA","SWA","SWR","SXS",
    "TAM","TAP","TFL","THA","THY","TOM","TRA","TRS","TUA","TUI","UAE","UAL",
    "UPS","VIV","VLG","WJA","WUK","WZZ",
]

# ── helpers ────────────────────────────────────────────────────────────────────

def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def img_to_rgb565(path: Path) -> list[int]:
    img = Image.open(path).convert("RGBA")
    bg  = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    rgb = bg.convert("RGB").resize((W, H), Image.LANCZOS)
    return [to_rgb565(*rgb.getpixel((x, y))) for y in range(H) for x in range(W)]

# ── generate ───────────────────────────────────────────────────────────────────

# Collect all logo data first, then emit as ONE flat PROGMEM array.
found = []
for icao in INCLUDE:
    src = LOGO_DIR / f"airline_logo_{icao}.png"
    if not src.exists():
        print(f"  SKIP {icao} — not found in repo")
        continue
    found.append((icao, img_to_rgb565(src)))
    print(f"  OK {icao}")

PX = W * H   # pixels per logo

lines = [
    "// Auto-generated by gen_logos.py — do not edit manually.",
    f"// Source: images/airline_logos/   Size: {W}x{H} RGB565",
    "// Single flat array for fast compilation; binary-search lookup.",
    "#pragma once",
    "#include <pgmspace.h>",
    "#include <string.h>",
    "#include <ctype.h>",
    "",
    f"#define LOGO_SIZE   {W}",
    f"#define LOGO_PX     {PX}",
    f"#define LOGO_COUNT  {len(found)}",
    "",
    f"static const uint16_t LOGO_DATA[{len(found)} * LOGO_PX] PROGMEM = {{",
]
for icao, pixels in found:
    lines.append(f"  // {icao}")
    for i in range(0, len(pixels), W):
        row = pixels[i:i+W]
        lines.append("  " + ",".join(f"0x{v:04X}" for v in row) + ",")
lines += [
    "};",
    "",
    "struct AirlogoIdx { char icao[4]; uint16_t idx; };",
    f"static const AirlogoIdx LOGO_IDX[{len(found)}] PROGMEM = {{",
]
for i, (icao, _) in enumerate(found):
    lines.append(f'  {{"{icao}", {i}}},')
lines += [
    "};",
    "",
    "static const uint16_t* logoForCallsign(const char* cs) {",
    "  if (!cs || !cs[0]) return nullptr;",
    "  char key[4] = {0};",
    "  int n = 0;",
    "  while (n < 3 && cs[n] && isalpha((uint8_t)cs[n])) { key[n] = toupper((uint8_t)cs[n]); n++; }",
    "  if (n < 2) return nullptr;",
    "  int lo = 0, hi = LOGO_COUNT - 1;",
    "  while (lo <= hi) {",
    "    int mid = (lo + hi) / 2;",
    "    char mkey[4];",
    "    memcpy_P(mkey, LOGO_IDX[mid].icao, 4);",
    "    int cmp = strncmp(key, mkey, 3);",
    "    if (cmp == 0) {",
    "      uint16_t idx = pgm_read_word(&LOGO_IDX[mid].idx);",
    "      return LOGO_DATA + (uint32_t)idx * LOGO_PX;",
    "    }",
    "    if (cmp < 0) hi = mid - 1; else lo = mid + 1;",
    "  }",
    "  return nullptr;",
    "}",
    "",
    "static void drawLogo(Arduino_GFX* gfx, int16_t cx, int16_t cy, const uint16_t* data) {",
    "  if (!data) return;",
    "  gfx->draw16bitRGBBitmap(cx - LOGO_SIZE/2, cy - LOGO_SIZE/2, (uint16_t*)data, LOGO_SIZE, LOGO_SIZE);",
    "}",
]

DST.write_text("\n".join(lines) + "\n", encoding="utf-8")
total_kb = len(found) * W * H * 2 // 1024
print(f"\nWritten {len(found)}/{len(INCLUDE)} logos to {DST.name}")
print(f"PROGMEM usage: ~{len(found) * W * H * 2 // 1024} KB")
